name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
  
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      actions: write
      contents: read
          
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # -
      #   name: Build image (amd64)
      #   uses: docker/build-push-action@v5
      #   with:
      #     file: ./Dockerfile
      #     pull: false
      #     push: false
      #     load: true
      #     tags: discordsearchscraper:amd64
      #     platforms: linux/amd64
      # -
      #   name: docker-slim (amd64)
      #   uses: kitabisa/docker-slim-action@v1.1.1
      #   env:
      #     DSLIM_HTTP_PROBE: false
      #     DSLIM_PULL: false
      #     DSLIM_IMAGE_BUILD_ARCH: amd64
      #   with:
      #     target: discordsearchscraper:amd64
      #     overwrite: true
      -
        name: Build image (arm64)
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          pull: false
          push: false
          load: true
          tags: discordsearchscraper:arm64
          platforms: linux/arm64
      -
        name: docker-slim (arm64)
        uses: kitabisa/docker-slim-action@v1.1.1
        env:
          DSLIM_HTTP_PROBE: false
          DSLIM_PULL: false
          DSLIM_IMAGE_BUILD_ARCH: arm64
        with:
          target: discordsearchscraper:arm64
          overwrite: true
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/discordsearchscraper:arm64
