name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
  
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      actions: write
      contents: read
          
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: false
          file: ./Dockerfile
          tags: "${{ github.repository }}:latest"
      -
        name: docker-slim GitHub Action
        uses: kitabisa/docker-slim-action@v1.1.1
        env:
          DSLIM_HTTP_PROBE: false
        with: 
          # Target container image (name or ID)
          target: "${{ github.repository }}:latest"
          overwrite: true
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        run: 
           docker tag ${{ github.repository }}:latest ${{ secrets.DOCKERHUB_USERNAME }}${{ github.repository }}:latest
           docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}:latest
